"""
Curated skill vocabulary for JD/resume extraction and fuzzy matching.
Extends coverage across common HR-tech and engineering stacks.
"""

from __future__ import annotations

# Multi-word first (longer keys matched before singles in extractor)
SKILL_PHRASES: tuple[str, ...] = (
    "machine learning",
    "deep learning",
    "natural language processing",
    "large language models",
    "computer vision",
    "data engineering",
    "data science",
    "business intelligence",
    "project management",
    "product management",
    "stakeholder management",
    "agile methodology",
    "ci cd",
    "ci/cd",
    "rest api",
    "graphql api",
    "microservices architecture",
    "cloud architecture",
    "system design",
    "object oriented design",
    "test driven development",
    "salesforce crm",
    "power bi",
    "tableau desktop",
    "google bigquery",
    "amazon s3",
    "amazon ec2",
    "azure devops",
    "git github",
    "unit testing",
    "integration testing",
    "prompt engineering",
    "vector databases",
    "lang chain",
)

SKILL_SINGLES: frozenset[str] = frozenset(
    {
        "python",
        "java",
        "javascript",
        "typescript",
        "go",
        "golang",
        "rust",
        "c++",
        "csharp",
        "c#",
        "ruby",
        "php",
        "scala",
        "kotlin",
        "swift",
        "r",
        "sql",
        "postgres",
        "postgresql",
        "mysql",
        "mongodb",
        "redis",
        "elasticsearch",
        "snowflake",
        "databricks",
        "spark",
        "airflow",
        "dbt",
        "kafka",
        "rabbitmq",
        "docker",
        "kubernetes",
        "terraform",
        "ansible",
        "jenkins",
        "github",
        "gitlab",
        "jira",
        "confluence",
        "excel",
        "pandas",
        "numpy",
        "scikit",
        "sklearn",
        "pytorch",
        "tensorflow",
        "keras",
        "opencv",
        "spacy",
        "nltk",
        "hadoop",
        "hive",
        "tableau",
        "looker",
        "fastapi",
        "django",
        "flask",
        "spring",
        "springboot",
        "nodejs",
        "node",
        "react",
        "vue",
        "angular",
        "nextjs",
        "graphql",
        "grpc",
        "aws",
        "gcp",
        "azure",
        "golang",
        "linux",
        "unix",
        "bash",
        "shell",
        "nginx",
        "figma",
        "notion",
        "salesforce",
        "servicenow",
        "workday",
        "sap",
        "oracle",
        "scrum",
        "kanban",
        "agile",
        "leadership",
        "communication",
        "nlp",
        "llm",
        "openai",
        "anthropic",
        "mvp",
    }
)


def all_lexicon_strings() -> list[str]:
    return list(SKILL_PHRASES) + sorted(SKILL_SINGLES)
